#%RAML 1.0 Library
types:
  employees: 
    type: array
    items: employee
  employee: 
    type: object
    properties: 
      id: string
      employee_name?: string
      employee_salary?: string
      employee_age?: string
      profile_image?: string